#include <iostream>
#include <string>
#include <vector>
#include <map>
#include <ostream>

using namespace std;

class CodeGenerator;

class Node;
class Expression;
class Statement;
class Integer;
class Real;
class Char;
class Boolean;
class ConstValue;
class Identifier;
class ConstDeclaration;
class TypeDeclaration;
class VarDeclaration;
class AstType;
class EnumType;
class AstArrayType;
class RecordType;
class ConstRangeType;
class EnumRangeType;
class FieldDeclaration;
class FuncDeclaration;
class Parameter;
class Routine;
class Program;
class AssignStatement;
class BinaryExpression;
class ArrayReference;
class RecordReference;
class FunctionCall;
class SysFunctionCall;
class ProcedureCall;
class SysProcedureCall;
class IfStatement;
class RepeatStatement;
class WhileStatement;
class ForStatement;
class CaseStatement;
class CaseExpression;
class GotoStatement;
class CompoundStatement;